### ISSUE TITLE
Search Bar overlapped by Menu Window on mobile devices.

### ISSUE THREAD

**Issue by Yash094** [thirdweb-dev/docs-v2#144]
# Issue:

Search Bar overlapped by Menu Window on mobile devices.

# Reproduction Steps:
1. Open the docs site with any mobile device
2. Click on the hamburger Menu icon to display menu items
3. Click on the search icon
4. The keyboard will popup but the search input will be overlapped by Menu Window

# Expected Behaviour:
Menu window should automatically get closed and search window with search input should popup.

Screenshot Attached:
![Screenshot_2024-02-03-03-16-13-53_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/thirdweb-dev/docs-v2/assets/67926590/b116a941-401f-4c2d-83ea-55bf18a22f3d)
![Screenshot_2024-02-03-03-16-19-14_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/thirdweb-dev/docs-v2/assets/67926590/9866f0ec-6805-451f-8127-0bb8342002fc)

**Comment by MananTank** [comment]
Fixed in #200
