### ISSUE TITLE
404 on website https://portal.thirdweb.com/connect

### ISSUE THREAD

**Issue by scenaristeur** [thirdweb-dev/docs-v2#310]
hi, on this page https://portal.thirdweb.com/connect, those two buttons 

![image](https://github.com/thirdweb-dev/docs-v2/assets/4020744/eed64556-15ba-41b5-81ff-799765cb46ce)

give me 404

![image](https://github.com/thirdweb-dev/docs-v2/assets/4020744/d4bf503e-18a6-4b5b-8624-7afa0cb1085f)

**Comment by MananTank** [comment]
Thanks @scenaristeur for reporting this issue. Fixed in #321
